# Welcome to Jekyll!

# Site settings
title: Toko Online
dev: Putri Dinar
logo: /assets/images/logo.webp
description: > # this means to ignore newlines until "baseurl:"
  Toko Online Jekyll Static Whatsapp Order.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tokoonline.pages.dev" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown
CLIENT_KEY: SB-Mid-client-rAWcUqggvu92k9Ul
SERVER_KEY: SB-Mid-server-OlcPbvosi7DN_co_ZPkDKmnA
wa_key: 6281111191209

placeholder: /assets/images/placeholder.jpg

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Custom Collections
collections:
  products:
    output: true

# Collection Defaults
defaults:
- scope:
    type: products
  values:
    layout: product

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  permalinks:
    categories: '/category/:name/'
    tags: '/tag/:name/'